/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic. 

API version: 1.0-rev2
Contact: support@veeam.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// ERetentionPolicyType Type of the retention policy.
type ERetentionPolicyType string

// List of ERetentionPolicyType
const (
	ERETENTIONPOLICYTYPE_RESTORE_POINTS ERetentionPolicyType = "RestorePoints"
	ERETENTIONPOLICYTYPE_DAYS ERetentionPolicyType = "Days"
)

// All allowed values of ERetentionPolicyType enum
var AllowedERetentionPolicyTypeEnumValues = []ERetentionPolicyType{
	"RestorePoints",
	"Days",
}

func (v *ERetentionPolicyType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ERetentionPolicyType(value)
	for _, existing := range AllowedERetentionPolicyTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ERetentionPolicyType", value)
}

// NewERetentionPolicyTypeFromValue returns a pointer to a valid ERetentionPolicyType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewERetentionPolicyTypeFromValue(v string) (*ERetentionPolicyType, error) {
	ev := ERetentionPolicyType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ERetentionPolicyType: valid values are %v", v, AllowedERetentionPolicyTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ERetentionPolicyType) IsValid() bool {
	for _, existing := range AllowedERetentionPolicyTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ERetentionPolicyType value
func (v ERetentionPolicyType) Ptr() *ERetentionPolicyType {
	return &v
}

type NullableERetentionPolicyType struct {
	value *ERetentionPolicyType
	isSet bool
}

func (v NullableERetentionPolicyType) Get() *ERetentionPolicyType {
	return v.value
}

func (v *NullableERetentionPolicyType) Set(val *ERetentionPolicyType) {
	v.value = val
	v.isSet = true
}

func (v NullableERetentionPolicyType) IsSet() bool {
	return v.isSet
}

func (v *NullableERetentionPolicyType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableERetentionPolicyType(val *ERetentionPolicyType) *NullableERetentionPolicyType {
	return &NullableERetentionPolicyType{value: val, isSet: true}
}

func (v NullableERetentionPolicyType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableERetentionPolicyType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

